import { Element } from '../types/element';

export const elements: Element[] = [
  {
    atomicNumber: 1,
    symbol: 'H',
    name: 'Hydrogen',
    atomicWeight: 1.008,
    category: 'nonmetal',
    electronConfiguration: '1s1',
    density: 0.08988,
    meltingPoint: -259.16,
    boilingPoint: -252.87,
    phase: 'Gas',
  },
  {
    atomicNumber: 2,
    symbol: 'He',
    name: 'Helium',
    atomicWeight: 4.0026,
    category: 'noble gas',
    electronConfiguration: '1s2',
    density: 0.1786,
    meltingPoint: null,
    boilingPoint: -268.93,
    phase: 'Gas',
  },
  {
    atomicNumber: 3,
    symbol: 'Li',
    name: 'Lithium',
    atomicWeight: 6.94,
    category: 'alkali metal',
    electronConfiguration: '[He] 2s1',
    density: 0.534,
    meltingPoint: 180.54,
    boilingPoint: 1342,
    phase: 'Solid',
  },
  {
    atomicNumber: 4,
    symbol: 'Be',
    name: 'Beryllium',
    atomicWeight: 9.0122,
    category: 'alkaline earth metal',
    electronConfiguration: '[He] 2s2',
    density: 1.848,
    meltingPoint: 1287,
    boilingPoint: 2469,
    phase: 'Solid',
  },
  {
    atomicNumber: 5,
    symbol: 'B',
    name: 'Boron',
    atomicWeight: 10.81,
    category: 'metalloid',
    electronConfiguration: '[He] 2s2 2p1',
    density: 2.34,
    meltingPoint: 2076,
    boilingPoint: 3927,
    phase: 'Solid',
  },
  {
    atomicNumber: 6,
    symbol: 'C',
    name: 'Carbon',
    atomicWeight: 12.011,
    category: 'nonmetal',
    electronConfiguration: '[He] 2s2 2p2',
    density: 2.267,
    meltingPoint: 3550,
    boilingPoint: 4827,
    phase: 'Solid',
  },
  {
    atomicNumber: 7,
    symbol: 'N',
    name: 'Nitrogen',
    atomicWeight: 14.007,
    category: 'nonmetal',
    electronConfiguration: '[He] 2s2 2p3',
    density: 1.2506,
    meltingPoint: -210.00,
    boilingPoint: -195.79,
    phase: 'Gas',
  },
  {
    atomicNumber: 8,
    symbol: 'O',
    name: 'Oxygen',
    atomicWeight: 15.999,
    category: 'nonmetal',
    electronConfiguration: '[He] 2s2 2p4',
    density: 1.429,
    meltingPoint: -218.79,
    boilingPoint: -182.95,
    phase: 'Gas',
  },
  {
    atomicNumber: 9,
    symbol: 'F',
    name: 'Fluorine',
    atomicWeight: 18.998,
    category: 'halogen',
    electronConfiguration: '[He] 2s2 2p5',
    density: 1.696,
    meltingPoint: -219.67,
    boilingPoint: -188.11,
    phase: 'Gas',
  },
  {
    atomicNumber: 10,
    symbol: 'Ne',
    name: 'Neon',
    atomicWeight: 20.180,
    category: 'noble gas',
    electronConfiguration: '[He] 2s2 2p6',
    density: 0.9002,
    meltingPoint: -248.59,
    boilingPoint: -246.08,
    phase: 'Gas',
  },
  {
    atomicNumber: 11,
    symbol: 'Na',
    name: 'Sodium',
    atomicWeight: 22.990,
    category: 'alkali metal',
    electronConfiguration: '[Ne] 3s1',
    density: 0.971,
    meltingPoint: 97.79,
    boilingPoint: 883,
    phase: 'Solid',
  },
  {
    atomicNumber: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    atomicWeight: 24.305,
    category: 'alkaline earth metal',
    electronConfiguration: '[Ne] 3s2',
    density: 1.738,
    meltingPoint: 650,
    boilingPoint: 1091,
    phase: 'Solid',
  },
  {
    atomicNumber: 13,
    symbol: 'Al',
    name: 'Aluminium',
    atomicWeight: 26.981,
    category: 'post-transition metal',
    electronConfiguration: '[Ne] 3s2 3p1',
    density: 2.70,
    meltingPoint: 660.32,
    boilingPoint: 2470,
    phase: 'Solid',
  },
  {
    atomicNumber: 14,
    symbol: 'Si',
    name: 'Silicon',
    atomicWeight: 28.085,
    category: 'metalloid',
    electronConfiguration: '[Ne] 3s2 3p2',
    density: 2.3296,
    meltingPoint: 1414,
    boilingPoint: 3265,
    phase: 'Solid',
  },
  {
    atomicNumber: 15,
    symbol: 'P',
    name: 'Phosphorus',
    atomicWeight: 30.974,
    category: 'nonmetal',
    electronConfiguration: '[Ne] 3s2 3p3',
    density: 1.82,
    meltingPoint: 44.2,
    boilingPoint: 280.5,
    phase: 'Solid',
  },
  {
    atomicNumber: 16,
    symbol: 'S',
    name: 'Sulfur',
    atomicWeight: 32.06,
    category: 'nonmetal',
    electronConfiguration: '[Ne] 3s2 3p4',
    density: 2.067,
    meltingPoint: 115.21,
    boilingPoint: 444.6,
    phase: 'Solid',
  },
  {
    atomicNumber: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    atomicWeight: 35.45,
    category: 'halogen',
    electronConfiguration: '[Ne] 3s2 3p5',
    density: 3.214,
    meltingPoint: -101.5,
    boilingPoint: -34.04,
    phase: 'Gas',
  },
  {
    atomicNumber: 18,
    symbol: 'Ar',
    name: 'Argon',
    atomicWeight: 39.948,
    category: 'noble gas',
    electronConfiguration: '[Ne] 3s2 3p6',
    density: 1.784,
    meltingPoint: -189.35,
    boilingPoint: -185.85,
    phase: 'Gas',
  },
  {
    atomicNumber: 19,
    symbol: 'K',
    name: 'Potassium',
    atomicWeight: 39.098,
    category: 'alkali metal',
    electronConfiguration: '[Ar] 4s1',
    density: 0.862,
    meltingPoint: 63.5,
    boilingPoint: 759,
    phase: 'Solid',
  },
  {
    atomicNumber: 20,
    symbol: 'Ca',
    name: 'Calcium',
    atomicWeight: 40.078,
    category: 'alkaline earth metal',
    electronConfiguration: '[Ar] 4s2',
    density: 1.54,
    meltingPoint: 842,
    boilingPoint: 1484,
    phase: 'Solid',
  },
  {
    atomicNumber: 21,
    symbol: 'Sc',
    name: 'Scandium',
    atomicWeight: 44.956,
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d1 4s2',
    density: 2.985,
    meltingPoint: 1541,
    boilingPoint: 2836,
    phase: 'Solid',
  },
  {
    atomicNumber: 22,
    symbol: 'Ti',
    name: 'Titanium',
    atomicWeight: 47.867,
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d2 4s2',
    density: 4.506,
    meltingPoint: 1668,
    boilingPoint: 3287,
    phase: 'Solid',
  },
  {
    atomicNumber: 23,
    symbol: 'V',
    name: 'Vanadium',
    atomicWeight: 50.942,
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d3 4s2',
    density: 6.11,
    meltingPoint: 1910,
    boilingPoint: 3407,
    phase: 'Solid',
  },
  {
    atomicNumber: 24,
    symbol: 'Cr',
    name: 'Chromium',
    atomicWeight: 51.996,
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d5 4s1',
    density: 7.19,
    meltingPoint: 1907,
    boilingPoint: 2671,
    phase: 'Solid',
  },
  {
    atomicNumber: 25,
    symbol: 'Mn',
    name: 'Manganese',
    atomicWeight: 54.938,
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d5 4s2',
    density: 7.21,
    meltingPoint: 1246,
    boilingPoint: 2061,
    phase: 'Solid',
  },
  {
    atomicNumber: 26,
    symbol: 'Fe',
    name: 'Iron',
    atomicWeight: 55.845,
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d6 4s2',
    density: 7.874,
    meltingPoint: 1538,
    boilingPoint: 2862,
    phase: 'Solid',
  },
  {
    atomicNumber: 27,
    symbol: 'Co',
    name: 'Cobalt',
    atomicWeight: 58.933,
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d7 4s2',
    density: 8.90,
    meltingPoint: 1495,
    boilingPoint: 2927,
    phase: 'Solid',
  },
  {
    atomicNumber: 28,
    symbol: 'Ni',
    name: 'Nickel',
    atomicWeight: 58.693,
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d8 4s2',
    density: 8.908,
    meltingPoint: 1455,
    boilingPoint: 2730,
    phase: 'Solid',
  },
  {
    atomicNumber: 29,
    symbol: 'Cu',
    name: 'Copper',
    atomicWeight: 63.546,
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d10 4s1',
    density: 8.96,
    meltingPoint: 1084.62,
    boilingPoint: 2562,
    phase: 'Solid',
  },
  {
    atomicNumber: 30,
    symbol: 'Zn',
    name: 'Zinc',
    atomicWeight: 65.38,
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d10 4s2',
    density: 7.14,
    meltingPoint: 419.53,
    boilingPoint: 907,
    phase: 'Solid',
  },
  {
    atomicNumber: 31,
    symbol: 'Ga',
    name: 'Gallium',
    atomicWeight: 69.723,
    category: 'post-transition metal',
    electronConfiguration: '[Ar] 3d10 4s2 4p1',
    density: 5.91,
    meltingPoint: 29.76,
    boilingPoint: 2204,
    phase: 'Solid',
  },
  {
    atomicNumber: 32,
    symbol: 'Ge',
    name: 'Germanium',
    atomicWeight: 72.63,
    category: 'metalloid',
    electronConfiguration: '[Ar] 3d10 4s2 4p2',
    density: 5.323,
    meltingPoint: 938.25,
    boilingPoint: 2820,
    phase: 'Solid',
  },
  {
    atomicNumber: 33,
    symbol: 'As',
    name: 'Arsenic',
    atomicWeight: 74.922,
    category: 'metalloid',
    electronConfiguration: '[Ar] 3d10 4s2 4p3',
    density: 5.776,
    meltingPoint: 817,
    boilingPoint: 613,
    phase: 'Solid',
  },
  {
    atomicNumber: 34,
    symbol: 'Se',
    name: 'Selenium',
    atomicWeight: 78.971,
    category: 'nonmetal',
    electronConfiguration: '[Ar] 3d10 4s2 4p4',
    density: 4.81,
    meltingPoint: 221,
    boilingPoint: 685,
    phase: 'Solid',
  },
  {
    atomicNumber: 35,
    symbol: 'Br',
    name: 'Bromine',
    atomicWeight: 79.904,
    category: 'halogen',
    electronConfiguration: '[Ar] 3d10 4s2 4p5',
    density: 3.12,
    meltingPoint: -7.2,
    boilingPoint: 58.8,
    phase: 'Liquid',
  },
  {
    atomicNumber: 36,
    symbol: 'Kr',
    name: 'Krypton',
    atomicWeight: 83.798,
    category: 'noble gas',
    electronConfiguration: '[Ar] 3d10 4s2 4p6',
    density: 3.749,
    meltingPoint: -157.36,
    boilingPoint: -153.22,
    phase: 'Gas',
  },
  {
    atomicNumber: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    atomicWeight: 85.468,
    category: 'alkali metal',
    electronConfiguration: '[Kr] 5s1',
    density: 1.532,
    meltingPoint: 39.31,
    boilingPoint: 688,
    phase: 'Solid',
  },
  {
    atomicNumber: 38,
    symbol: 'Sr',
    name: 'Strontium',
    atomicWeight: 87.62,
    category: 'alkaline earth metal',
    electronConfiguration: '[Kr] 5s2',
    density: 2.64,
    meltingPoint: 777,
    boilingPoint: 1382,
    phase: 'Solid',
  },
  {
    atomicNumber: 39,
    symbol: 'Y',
    name: 'Yttrium',
    atomicWeight: 88.906,
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d1 5s2',
    density: 4.47,
    meltingPoint: 1526,
    boilingPoint: 3336,
    phase: 'Solid',
  },
  {
    atomicNumber: 40,
    symbol: 'Zr',
    name: 'Zirconium',
    atomicWeight: 91.224,
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d2 5s2',
    density: 6.52,
    meltingPoint: 1855,
    boilingPoint: 4409,
    phase: 'Solid',
  },
  {
    atomicNumber: 41,
    symbol: 'Nb',
    name: 'Niobium',
    atomicWeight: 92.906,
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d4 5s1',
    density: 8.57,
    meltingPoint: 2477,
    boilingPoint: 4744,
    phase: 'Solid',
  },
  {
    atomicNumber: 42,
    symbol: 'Mo',
    name: 'Molybdenum',
    atomicWeight: 95.95,
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d5 5s1',
    density: 10.28,
    meltingPoint: 2623,
    boilingPoint: 4639,
    phase: 'Solid',
  },
  {
    atomicNumber: 43,
    symbol: 'Tc',
    name: 'Technetium',
    atomicWeight: 98,
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d5 5s2',
    density: 11.5,
    meltingPoint: 2157,
    boilingPoint: 4265,
    phase: 'Solid',
  },
  {
    atomicNumber: 44,
    symbol: 'Ru',
    name: 'Ruthenium',
    atomicWeight: 101.07,
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d7 5s1',
    density: 12.37,
    meltingPoint: 2334,
    boilingPoint: 4150,
    phase: 'Solid',
  },
  {
    atomicNumber: 45,
    symbol: 'Rh',
    name: 'Rhodium',
    atomicWeight: 102.91,
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d8 5s1',
    density: 12.41,
    meltingPoint: 1964,
    boilingPoint: 3695,
    phase: 'Solid',
  },
  {
    atomicNumber: 46,
    symbol: 'Pd',
    name: 'Palladium',
    atomicWeight: 106.42,
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d10',
    density: 12.02,
    meltingPoint: 1554.9,
    boilingPoint: 2963,
    phase: 'Solid',
  },
  {
    atomicNumber: 47,
    symbol: 'Ag',
    name: 'Silver',
    atomicWeight: 107.87,
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d10 5s1',
    density: 10.49,
    meltingPoint: 961.78,
    boilingPoint: 2162,
    phase: 'Solid',
  },
  {
    atomicNumber: 48,
    symbol: 'Cd',
    name: 'Cadmium',
    atomicWeight: 112.41,
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d10 5s2',
    density: 8.65,
    meltingPoint: 321.07,
    boilingPoint: 767,
    phase: 'Solid',
  },
  {
    atomicNumber: 49,
    symbol: 'In',
    name: 'Indium',
    atomicWeight: 114.82,
    category: 'post-transition metal',
    electronConfiguration: '[Kr] 4d10 5s2 5p1',
    density: 7.31,
    meltingPoint: 156.6,
    boilingPoint: 2072,
    phase: 'Solid',
  },
  {
    atomicNumber: 50,
    symbol: 'Sn',
    name: 'Tin',
    atomicWeight: 118.71,
    category: 'post-transition metal',
    electronConfiguration: '[Kr] 4d10 5s2 5p2',
    density: 7.287,
    meltingPoint: 231.93,
    boilingPoint: 2602,
    phase: 'Solid',
  },
  {
    atomicNumber: 51,
    symbol: 'Sb',
    name: 'Antimony',
    atomicWeight: 121.76,
    category: 'metalloid',
    electronConfiguration: '[Kr] 4d10 5s2 5p3',
    density: 6.685,
    meltingPoint: 630.63,
    boilingPoint: 1587,
    phase: 'Solid',
  },
  {
    atomicNumber: 52,
    symbol: 'Te',
    name: 'Tellurium',
    atomicWeight: 127.60,
    category: 'metalloid',
    electronConfiguration: '[Kr] 4d10 5s2 5p4',
    density: 6.24,
    meltingPoint: 449.51,
    boilingPoint: 988,
    phase: 'Solid',
  },
  {
    atomicNumber: 53,
    symbol: 'I',
    name: 'Iodine',
    atomicWeight: 126.90,
    category: 'halogen',
    electronConfiguration: '[Kr] 4d10 5s2 5p5',
    density: 4.933,
    meltingPoint: 113.7,
    boilingPoint: 184.3,
    phase: 'Solid',
  },
  {
    atomicNumber: 54,
    symbol: 'Xe',
    name: 'Xenon',
    atomicWeight: 131.29,
    category: 'noble gas',
    electronConfiguration: '[Kr] 4d10 5s2 5p6',
    density: 5.894,
    meltingPoint: -111.8,
    boilingPoint: -108.1,
    phase: 'Gas',
  },
  {
    atomicNumber: 55,
    symbol: 'Cs',
    name: 'Cesium',
    atomicWeight: 132.91,
    category: 'alkali metal',
    electronConfiguration: '[Xe] 6s1',
    density: 1.93,
    meltingPoint: 28.44,
    boilingPoint: 671,
    phase: 'Solid',
  },
  {
    atomicNumber: 56,
    symbol: 'Ba',
    name: 'Barium',
    atomicWeight: 137.33,
    category: 'alkaline earth metal',
    electronConfiguration: '[Xe] 6s2',
    density: 3.594,
    meltingPoint: 727,
    boilingPoint: 1845,
    phase: 'Solid',
  },
  {
    atomicNumber: 57,
    symbol: 'La',
    name: 'Lanthanum',
    atomicWeight: 138.91,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 5d1 6s2',
    density: 6.145,
    meltingPoint: 920,
    boilingPoint: 3464,
    phase: 'Solid',
  },
  {
    atomicNumber: 58,
    symbol: 'Ce',
    name: 'Cerium',
    atomicWeight: 140.12,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f1 5d1 6s2',
    density: 6.770,
    meltingPoint: 798,
    boilingPoint: 3360,
    phase: 'Solid',
  },
  {
    atomicNumber: 59,
    symbol: 'Pr',
    name: 'Praseodymium',
    atomicWeight: 140.91,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f3 6s2',
    density: 6.773,
    meltingPoint: 931,
    boilingPoint: 3290,
    phase: 'Solid',
  },
  {
    atomicNumber: 60,
    symbol: 'Nd',
    name: 'Neodymium',
    atomicWeight: 144.24,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f4 6s2',
    density: 7.007,
    meltingPoint: 1024,
    boilingPoint: 3074,
    phase: 'Solid',
  },
  {
    atomicNumber: 61,
    symbol: 'Pm',
    name: 'Promethium',
    atomicWeight: 145,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f5 6s2',
    density: 7.26,
    meltingPoint: 1100,
    boilingPoint: 3000,
    phase: 'Solid',
  },
  {
    atomicNumber: 62,
    symbol: 'Sm',
    name: 'Samarium',
    atomicWeight: 150.36,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f6 6s2',
    density: 7.52,
    meltingPoint: 1072,
    boilingPoint: 1794,
    phase: 'Solid',
  },
  {
    atomicNumber: 63,
    symbol: 'Eu',
    name: 'Europium',
    atomicWeight: 151.96,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f7 6s2',
    density: 5.264,
    meltingPoint: 826,
    boilingPoint: 1529,
    phase: 'Solid',
  },
  {
    atomicNumber: 64,
    symbol: 'Gd',
    name: 'Gadolinium',
    atomicWeight: 157.25,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f7 5d1 6s2',
    density: 7.900,
    meltingPoint: 1313,
    boilingPoint: 3273,
    phase: 'Solid',
  },
  {
    atomicNumber: 65,
    symbol: 'Tb',
    name: 'Terbium',
    atomicWeight: 158.93,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f9 6s2',
    density: 8.230,
    meltingPoint: 1356,
    boilingPoint: 3230,
    phase: 'Solid',
  },
  {
    atomicNumber: 66,
    symbol: 'Dy',
    name: 'Dysprosium',
    atomicWeight: 162.50,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f10 6s2',
    density: 8.540,
    meltingPoint: 1412,
    boilingPoint: 2562,
    phase: 'Solid',
  },
  {
    atomicNumber: 67,
    symbol: 'Ho',
    name: 'Holmium',
    atomicWeight: 164.93,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f11 6s2',
    density: 8.800,
    meltingPoint: 1474,
    boilingPoint: 2700,
    phase: 'Solid',
  },
  {
    atomicNumber: 68,
    symbol: 'Er',
    name: 'Erbium',
    atomicWeight: 167.26,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f12 6s2',
    density: 9.066,
    meltingPoint: 1529,
    boilingPoint: 2868,
    phase: 'Solid',
  },
  {
    atomicNumber: 69,
    symbol: 'Tm',
    name: 'Thulium',
    atomicWeight: 168.93,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f13 6s2',
    density: 9.321,
    meltingPoint: 1545,
    boilingPoint: 1950,
    phase: 'Solid',
  },
  {
    atomicNumber: 70,
    symbol: 'Yb',
    name: 'Ytterbium',
    atomicWeight: 173.05,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f14 6s2',
    density: 6.965,
    meltingPoint: 819,
    boilingPoint: 1196,
    phase: 'Solid',
  },
  {
    atomicNumber: 71,
    symbol: 'Lu',
    name: 'Lutetium',
    atomicWeight: 174.97,
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f14 5d1 6s2',
    density: 9.841,
    meltingPoint: 1663,
    boilingPoint: 3402,
    phase: 'Solid',
  },
  {
    atomicNumber: 72,
    symbol: 'Hf',
    name: 'Hafnium',
    atomicWeight: 178.49,
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f14 5d2 6s2',
    density: 13.31,
    meltingPoint: 2233,
    boilingPoint: 4603,
    phase: 'Solid',
  },
  {
    atomicNumber: 73,
    symbol: 'Ta',
    name: 'Tantalum',
    atomicWeight: 180.95,
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f14 5d3 6s2',
    density: 16.654,
    meltingPoint: 3017,
    boilingPoint: 5458,
    phase: 'Solid',
  },
  {
    atomicNumber: 74,
    symbol: 'W',
    name: 'Tungsten',
    atomicWeight: 183.84,
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f14 5d4 6s2',
    density: 19.25,
    meltingPoint: 3422,
    boilingPoint: 5555,
    phase: 'Solid',
  },
  {
    atomicNumber: 75,
    symbol: 'Re',
    name: 'Rhenium',
    atomicWeight: 186.21,
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f14 5d5 6s2',
    density: 21.02,
    meltingPoint: 3186,
    boilingPoint: 5596,
    phase: 'Solid',
  },
  {
    atomicNumber: 76,
    symbol: 'Os',
    name: 'Osmium',
    atomicWeight: 190.23,
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f14 5d6 6s2',
    density: 22.59,
    meltingPoint: 3033,
    boilingPoint: 5012,
    phase: 'Solid',
  },
  {
    atomicNumber: 77,
    symbol: 'Ir',
    name: 'Iridium',
    atomicWeight: 192.22,
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f14 5d7 6s2',
    density: 22.56,
    meltingPoint: 2446,
    boilingPoint: 4428,
    phase: 'Solid',
  },
  {
    atomicNumber: 78,
    symbol: 'Pt',
    name: 'Platinum',
    atomicWeight: 195.08,
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f14 5d9 6s1',
    density: 21.45,
    meltingPoint: 1768.3,
    boilingPoint: 3825,
    phase: 'Solid',
  },
  {
    atomicNumber: 79,
    symbol: 'Au',
    name: 'Gold',
    atomicWeight: 196.97,
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f14 5d10 6s1',
    density: 19.32,
    meltingPoint: 1064.18,
    boilingPoint: 2856,
    phase: 'Solid',
  },
  {
    atomicNumber: 80,
    symbol: 'Hg',
    name: 'Mercury',
    atomicWeight: 200.59,
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f14 5d10 6s2',
    density: 13.534,
    meltingPoint: -38.83,
    boilingPoint: 356.73,
    phase: 'Liquid',
  },
  {
    atomicNumber: 81,
    symbol: 'Tl',
    name: 'Thallium',
    atomicWeight: 204.38,
    category: 'post-transition metal',
    electronConfiguration: '[Xe] 4f14 5d10 6s2 6p1',
    density: 11.85,
    meltingPoint: 304,
    boilingPoint: 1473,
    phase: 'Solid',
  },
  {
    atomicNumber: 82,
    symbol: 'Pb',
    name: 'Lead',
    atomicWeight: 207.2,
    category: 'post-transition metal',
    electronConfiguration: '[Xe] 4f14 5d10 6s2 6p2',
    density: 11.34,
    meltingPoint: 327.46,
    boilingPoint: 1749,
    phase: 'Solid',
  },
  {
    atomicNumber: 83,
    symbol: 'Bi',
    name: 'Bismuth',
    atomicWeight: 208.98,
    category: 'post-transition metal',
    electronConfiguration: '[Xe] 4f14 5d10 6s2 6p3',
    density: 9.78,
    meltingPoint: 271.5,
    boilingPoint: 1564,
    phase: 'Solid',
  },
  {
    atomicNumber: 84,
    symbol: 'Po',
    name: 'Polonium',
    atomicWeight: 209,
    category: 'metalloid',
    electronConfiguration: '[Xe] 4f14 5d10 6s2 6p4',
    density: 9.32,
    meltingPoint: 254,
    boilingPoint: 962,
    phase: 'Solid',
  },
  {
    atomicNumber: 85,
    symbol: 'At',
    name: 'Astatine',
    atomicWeight: 210,
    category: 'halogen',
    electronConfiguration: '[Xe] 4f14 5d10 6s2 6p5',
    density: 7,
    meltingPoint: 302,
    boilingPoint: 337,
    phase: 'Solid',
  },
  {
    atomicNumber: 86,
    symbol: 'Rn',
    name: 'Radon',
    atomicWeight: 222,
    category: 'noble gas',
    electronConfiguration: '[Xe] 4f14 5d10 6s2 6p6',
    density: 9.73,
    meltingPoint: -71,
    boilingPoint: -61.7,
    phase: 'Gas',
  },
  {
    atomicNumber: 87,
    symbol: 'Fr',
    name: 'Francium',
    atomicWeight: 223,
    category: 'alkali metal',
    electronConfiguration: '[Rn] 7s1',
    density: 1.87,
    meltingPoint: 27,
    boilingPoint: 677,
    phase: 'Solid',
  },
  {
    atomicNumber: 88,
    symbol: 'Ra',
    name: 'Radium',
    atomicWeight: 226,
    category: 'alkaline earth metal',
    electronConfiguration: '[Rn] 7s2',
    density: 5.5,
    meltingPoint: 700,
    boilingPoint: 1737,
    phase: 'Solid',
  },
  {
    atomicNumber: 89,
    symbol: 'Ac',
    name: 'Actinium',
    atomicWeight: 227,
    category: 'actinide',
    electronConfiguration: '[Rn] 6d1 7s2',
    density: 10.07,
    meltingPoint: 1050,
    boilingPoint: 3200,
    phase: 'Solid',
  },
  {
    atomicNumber: 90,
    symbol: 'Th',
    name: 'Thorium',
    atomicWeight: 232.04,
    category: 'actinide',
    electronConfiguration: '[Rn] 6d2 7s2',
    density: 11.72,
    meltingPoint: 1750,
    boilingPoint: 4788,
    phase: 'Solid',
  },
  {
    atomicNumber: 91,
    symbol: 'Pa',
    name: 'Protactinium',
    atomicWeight: 231.04,
    category: 'actinide',
    electronConfiguration: '[Rn] 5f2 6d1 7s2',
    density: 15.37,
    meltingPoint: 1572,
    boilingPoint: 4000,
    phase: 'Solid',
  },
  {
    atomicNumber: 92,
    symbol: 'U',
    name: 'Uranium',
    atomicWeight: 238.03,
    category: 'actinide',
    electronConfiguration: '[Rn] 5f3 6d1 7s2',
    density: 18.95,
    meltingPoint: 1135,
    boilingPoint: 4131,
    phase: 'Solid',
  },
  {
    atomicNumber: 93,
    symbol: 'Np',
    name: 'Neptunium',
    atomicWeight: 237,
    category: 'actinide',
    electronConfiguration: '[Rn] 5f4 6d1 7s2',
    density: 20.45,
    meltingPoint: 644,
    boilingPoint: 3902,
    phase: 'Solid',
  },
  {
    atomicNumber: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    atomicWeight: 244,
    category: 'actinide',
    electronConfiguration: '[Rn] 5f6 7s2',
    density: 19.84,
    meltingPoint: 640,
    boilingPoint: 3228,
    phase: 'Solid',
  },
  {
    atomicNumber: 95,
    symbol: 'Am',
    name: 'Americium',
    atomicWeight: 243,
    category: 'actinide',
    electronConfiguration: '[Rn] 5f7 7s2',
    density: 12,
    meltingPoint: 1176,
    boilingPoint: 2011,
    phase: 'Solid',
  },
  {
    atomicNumber: 96,
    symbol: 'Cm',
    name: 'Curium',
    atomicWeight: 247,
    category: 'actinide',
    electronConfiguration: '[Rn] 5f7 6d1 7s2',
    density: 13.51,
    meltingPoint: 1340,
    boilingPoint: 3110,
    phase: 'Solid',
  },
  {
    atomicNumber: 97,
    symbol: 'Bk',
    name: 'Berkelium',
    atomicWeight: 247,
    category: 'actinide',
    electronConfiguration: '[Rn] 5f9 7s2',
    density: 14.79,
    meltingPoint: 986,
    boilingPoint: 2627,
    phase: 'Solid',
  },
  {
    atomicNumber: 98,
    symbol: 'Cf',
    name: 'Californium',
    atomicWeight: 251,
    category: 'actinide',
    electronConfiguration: '[Rn] 5f10 7s2',
    density: 15.1,
    meltingPoint: 900,
    boilingPoint: 1472,
    phase: 'Solid',
  },
  {
    atomicNumber: 99,
    symbol: 'Es',
    name: 'Einsteinium',
    atomicWeight: 252,
    category: 'actinide',
    electronConfiguration: '[Rn] 5f11 7s2',
    density: 8.84,
    meltingPoint: 860,
    boilingPoint: 996,
    phase: 'Solid',
  },
  {
    atomicNumber: 100,
    symbol: 'Fm',
    name: 'Fermium',
    atomicWeight: 257,
    category: 'actinide',
    electronConfiguration: '[Rn] 5f12 7s2',
    density: 9.7,
    meltingPoint: 1527,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 101,
    symbol: 'Md',
    name: 'Mendelevium',
    atomicWeight: 258,
    category: 'actinide',
    electronConfiguration: '[Rn] 5f13 7s2',
    density: 10.3,
    meltingPoint: 827,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 102,
    symbol: 'No',
    name: 'Nobelium',
    atomicWeight: 259,
    category: 'actinide',
    electronConfiguration: '[Rn] 5f14 7s2',
    density: 9.9,
    meltingPoint: 827,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 103,
    symbol: 'Lr',
    name: 'Lawrencium',
    atomicWeight: 262,
    category: 'actinide',
    electronConfiguration: '[Rn] 5f14 7s2 7p1',
    density: 15.6,
    meltingPoint: 1627,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 104,
    symbol: 'Rf',
    name: 'Rutherfordium',
    atomicWeight: 267,
    category: 'transition metal',
    electronConfiguration: '[Rn] 5f14 6d2 7s2',
    density: 23.2,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 105,
    symbol: 'Db',
    name: 'Dubnium',
    atomicWeight: 270,
    category: 'transition metal',
    electronConfiguration: '[Rn] 5f14 6d3 7s2',
    density: 29.3,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 106,
    symbol: 'Sg',
    name: 'Seaborgium',
    atomicWeight: 271,
    category: 'transition metal',
    electronConfiguration: '[Rn] 5f14 6d4 7s2',
    density: 35.0,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 107,
    symbol: 'Bh',
    name: 'Bohrium',
    atomicWeight: 270,
    category: 'transition metal',
    electronConfiguration: '[Rn] 5f14 6d5 7s2',
    density: 37.1,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 108,
    symbol: 'Hs',
    name: 'Hassium',
    atomicWeight: 277,
    category: 'transition metal',
    electronConfiguration: '[Rn] 5f14 6d6 7s2',
    density: 40.7,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 109,
    symbol: 'Mt',
    name: 'Meitnerium',
    atomicWeight: 278,
    category: 'transition metal',
    electronConfiguration: '[Rn] 5f14 6d7 7s2',
    density: null,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 110,
    symbol: 'Ds',
    name: 'Darmstadtium',
    atomicWeight: 281,
    category: 'transition metal',
    electronConfiguration: '[Rn] 5f14 6d8 7s2',
    density: null,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 111,
    symbol: 'Rg',
    name: 'Roentgenium',
    atomicWeight: 282,
    category: 'transition metal',
    electronConfiguration: '[Rn] 5f14 6d9 7s2',
    density: null,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 112,
    symbol: 'Cn',
    name: 'Copernicium',
    atomicWeight: 285,
    category: 'transition metal',
    electronConfiguration: '[Rn] 5f14 6d10 7s2',
    density: 14.0,
    meltingPoint: null,
    boilingPoint: 357,
    phase: 'Gas',
  },
  {
    atomicNumber: 113,
    symbol: 'Nh',
    name: 'Nihonium',
    atomicWeight: 286,
    category: 'post-transition metal',
    electronConfiguration: '[Rn] 5f14 6d10 7s2 7p1',
    density: 16.0,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 114,
    symbol: 'Fl',
    name: 'Flerovium',
    atomicWeight: 289,
    category: 'post-transition metal',
    electronConfiguration: '[Rn] 5f14 6d10 7s2 7p2',
    density: null,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 115,
    symbol: 'Mc',
    name: 'Moscovium',
    atomicWeight: 290,
    category: 'post-transition metal',
    electronConfiguration: '[Rn] 5f14 6d10 7s2 7p3',
    density: null,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 116,
    symbol: 'Lv',
    name: 'Livermorium',
    atomicWeight: 293,
    category: 'post-transition metal',
    electronConfiguration: '[Rn] 5f14 6d10 7s2 7p4',
    density: null,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 117,
    symbol: 'Ts',
    name: 'Tennessine',
    atomicWeight: 294,
    category: 'halogen',
    electronConfiguration: '[Rn] 5f14 6d10 7s2 7p5',
    density: null,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Solid',
  },
  {
    atomicNumber: 118,
    symbol: 'Og',
    name: 'Oganesson',
    atomicWeight: 294,
    category: 'noble gas',
    electronConfiguration: '[Rn] 5f14 6d10 7s2 7p6',
    density: null,
    meltingPoint: null,
    boilingPoint: null,
    phase: 'Gas',
  },
];