export const facts: { [key: string]: string } = {
  // Nonmetals
  H: "Hydrogen is the most abundant element in the universe.",
  He: "Helium is the second lightest and second most abundant element in the observable universe.",
  Li: "Lithium is used in rechargeable batteries for mobile phones, laptops, digital cameras, and electric vehicles.",
  Be: "Beryllium is used in aerospace materials because of its light weight and high melting point.",
  B: "Boron is essential in small amounts for plant growth and is used in borosilicate glass.",
  C: "Carbon is the basis of life on Earth and is found in all living organisms.",
  N: "Nitrogen makes up about 78% of Earth's atmosphere.",
  O: "Oxygen is necessary for respiration in most living organisms.",
  F: "Fluorine is the most reactive and electronegative element.",
  Ne: "Neon is commonly used in neon signs for advertising due to its bright reddish-orange glow.",

  // Alkali Metals
  Na: "Sodium is highly reactive and is essential for nerve function in living organisms.",
  Mg: "Magnesium burns with a bright white light and is used in fireworks and flares.",
  Al: "Aluminum is lightweight, corrosion-resistant, and is widely used in packaging and construction.",
  Si: "Silicon is the main component of electronic circuits and semiconductors.",
  P: "Phosphorus is a key ingredient in fertilizers and is essential for plant growth.",
  S: "Sulfur is used in the production of sulfuric acid, one of the most important industrial chemicals.",
  Cl: "Chlorine is used to disinfect water and is essential for maintaining hygiene in pools.",
  Ar: "Argon is used in incandescent and fluorescent lighting due to its inert properties.",

  // Transition Metals
  K: "Potassium is vital for the function of all living cells.",
  Ca: "Calcium is essential for healthy bones and teeth in humans and animals.",
  Sc: "Scandium is used in aerospace components and sports equipment due to its strength and lightweight properties.",
  Ti: "Titanium is strong, lightweight, and resistant to corrosion, making it valuable in aerospace and medical implants.",
  V: "Vanadium is added to steel to increase its strength and resistance to corrosion.",
  Cr: "Chromium is used to produce stainless steel and to coat other metals to prevent corrosion.",
  Mn: "Manganese is essential in steel production and is used to make batteries.",
  Fe: "Iron is the most commonly used metal for construction and manufacturing, especially in steel.",
  Co: "Cobalt is used in batteries, especially in lithium-ion batteries, and in magnetic alloys.",
  Ni: "Nickel is used in the production of stainless steel and coins.",
  Cu: "Copper is one of the best conductors of electricity and is used in electrical wiring.",
  Zn: "Zinc is essential for human health and is used in galvanizing to prevent the rusting of steel.",
  Ga: "Gallium is used in semiconductors and has a low melting point, even melting in your hand.",
  Ge: "Germanium is a semiconductor material used in transistors and electronics.",
  As: "Arsenic is used in pesticides and herbicides but is toxic to humans in high doses.",
  Se: "Selenium is used in photocopiers and glassmaking and is essential in small amounts for human health.",
  Br: "Bromine is used in flame retardants and certain types of photographic film.",
  Kr: "Krypton is used in some types of photographic flashes for high-speed photography.",
  Rb: "Rubidium is used in atomic clocks and some types of glass.",
  Sr: "Strontium is used in fireworks for its bright red color and in medical imaging.",
  Y: "Yttrium is used in LED lights and phosphors in TV screens.",
  Zr: "Zirconium is used in nuclear reactors due to its low neutron absorption cross-section.",
  Nb: "Niobium is used to strengthen steel in pipelines and aerospace applications.",
  Mo: "Molybdenum is used in steel alloys for its strength and heat resistance.",
  Tc: "Technetium is the first artificially produced element and is used in medical imaging.",
  Ru: "Ruthenium is used in electronics and as a catalyst in some chemical reactions.",
  Rh: "Rhodium is one of the rarest and most valuable precious metals, often used in catalytic converters.",
  Pd: "Palladium is used in electronics, dentistry, and catalytic converters.",
  Ag: "Silver has the highest electrical conductivity of any metal and is widely used in jewelry.",
  Cd: "Cadmium is used in rechargeable batteries but is toxic and subject to environmental regulation.",
  In: "Indium is used in touchscreens, LCDs, and solders.",
  Sn: "Tin has been used for thousands of years to make bronze, an alloy of copper and tin.",
  Sb: "Antimony is used in flame retardants and some semiconductor devices.",
  Te: "Tellurium is used in solar panels and as an alloying agent in metals.",
  I: "Iodine is essential for the production of thyroid hormones in humans.",
  Xe: "Xenon is used in high-intensity lamps, such as those in car headlights and movie projectors.",

  // Lanthanides
  Cs: "Cesium is used in atomic clocks and has one of the lowest melting points of any metal.",
  Ba: "Barium is used in medical imaging to improve the contrast of X-ray images.",
  La: "Lanthanum is used in camera lenses and some types of batteries.",
  Ce: "Cerium is used in catalytic converters and in the polishing of glass.",
  Pr: "Praseodymium is used to make strong magnets and in aircraft engines.",
  Nd: "Neodymium is used to create powerful magnets found in many modern electronics like hard drives and headphones.",
  Pm: "Promethium is a radioactive element used in some types of atomic batteries.",
  Sm: "Samarium is used in high-strength magnets and in cancer treatments.",
  Eu: "Europium is used in phosphorescent materials for lighting and television screens.",
  Gd: "Gadolinium is used in medical imaging, particularly MRI scans.",
  Tb: "Terbium is used in green phosphors in lighting and screens.",
  Dy: "Dysprosium is used in magnets and nuclear reactor control rods.",
  Ho: "Holmium is used in lasers and magnets.",
  Er: "Erbium is used in optical fiber amplifiers and in some lasers.",
  Tm: "Thulium is used in portable X-ray devices.",
  Yb: "Ytterbium is used in some types of lasers and atomic clocks.",
  Lu: "Lutetium is used in PET scan detectors and some types of cancer treatments.",

  // Actinides
  Th: "Thorium is used in some types of nuclear reactors due to its radioactivity.",
  Pa: "Protactinium is one of the rarest naturally occurring elements.",
  U: "Uranium is used as fuel in nuclear reactors and weapons.",
  Np: "Neptunium is used in some types of neutron detectors.",
  Pu: "Plutonium is used in nuclear weapons and as a fuel source in some spacecraft.",
  Am: "Americium is used in smoke detectors and some industrial gauges.",
  Cm: "Curium is used in some types of space exploration equipment for its radioactive properties.",
  Bk: "Berkelium is primarily used for scientific research.",
  Cf: "Californium is used in neutron sources for scientific and industrial purposes.",
  Es: "Einsteinium is primarily used for scientific research.",
  Fm: "Fermium is primarily used in scientific research.",
  Md: "Mendelevium is named after Dmitri Mendeleev, who created the periodic table.",
  No: "Nobelium is named after Alfred Nobel, the founder of the Nobel Prize.",
  Lr: "Lawrencium is named after Ernest Lawrence, the inventor of the cyclotron.",

  // Superheavy Elements
  Rf: "Rutherfordium is named after physicist Ernest Rutherford, known as the father of nuclear physics.",
  Db: "Dubnium is named after the Russian city of Dubna, home to a major nuclear research center.",
  Sg: "Seaborgium is named after Glenn T. Seaborg, who contributed to the discovery of many elements.",
  Bh: "Bohrium is named after physicist Niels Bohr, a pioneer in atomic structure and quantum theory.",
  Hs: "Hassium is named after the German state of Hesse.",
  Mt: "Meitnerium is named after physicist Lise Meitner, who contributed to the discovery of nuclear fission.",
  Ds: "Darmstadtium is named after the German city of Darmstadt, where it was first synthesized.",
  Rg: "Roentgenium is named after Wilhelm Conrad Roentgen, the discoverer of X-rays.",
  Cn: "Copernicium is named after Nicolaus Copernicus, who formulated the heliocentric model of the solar system.",
  Nh: "Nihonium is named after Japan (Nihon), where it was discovered.",
  Fl: "Flerovium is named after the Flerov Laboratory of Nuclear Reactions in Russia.",
  Mc: "Moscovium is named after Moscow, Russia, where it was first synthesized.",
  Lv: "Livermorium is named after Lawrence Livermore National Laboratory in California.",
  Ts: "Tennessine is named after the U.S. state of Tennessee, recognizing contributions from Oak Ridge National Laboratory.",
  Og: "Oganesson is named after Russian physicist Yuri Oganessian, a pioneer in superheavy element research."
};